---
- name: Ensure Azure SQL PaaS Auditing is Enabled
  hosts: localhost
  connection: local
  become: true 
  gather_facts: False
  tasks:

    - name: Ensure SQL server exists
      azure.azcollection.azure_rm_sqlserver:
        resource_group: "{{ resourcegroup }}"
        name: "{{ sqlserver }}"
        location: eastus
        admin_username: "{{ admin }}"
        admin_password: "{{ password }}"


  vars: 
    admin: student
    location: eastus
    password: "RedHat123@!"
    resourcegroup: manulife_test_1
    sqldb: manulife_db  
    sqlserver: manulifesqlserver
    azure_ad_username: alex
    your_subscription_id: 6d1e140e-296e-42c1-b27a-26c101cc127f
    storage_account_key: 
    storage_acc: 
...
