---
- name: Azure SQL Database Hardening
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Download foo.conf
    ansible.builtin.get_url:
      url: https://aka.ms/InstallAzureCliRpmEl8Edge
      dest: /opt/azure-cli.rpm
    register: my_name  

  - debug:
      var: my_name
  - command: ls -l /opt/azure-cli.rpm
    register: my_file

  - debug:
      var: my_file
  - ansible.builtin.yum:
      name: /opt/azure-cli.rpm
      state: present  
      
  - name: Get details of Azure SQL Database
    azure_rm_sqldatabase_info:
      resource_group: manulife_test_1
      server_name: manulifesqlserver
    register: sqldb_info

  - name: Test the teach
    debug:
      var: sqldb_info
