## works with execution environment with python 3.9
---
- name: Azure SQL Database Hardening
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Download foo.conf
    ansible.builtin.get_url:
      url: https://aka.ms/InstallAzureCliRpmEl8Edge
      dest: /opt/azure-cli.rpm
    register: my_name  

  - debug:
      var: my_name
  - command: ls -l /opt/azure-cli.rpm


  - command: rpm -ivh --nodeps /opt/azure-cli.rpm
    register: azaz

  - debug:
      var: azaz

  - command: az --version
    register: aza

  - debug:
      var: aza
  - name: Enable Azure SQL audit policy
      command: az sql db audit-policy update --name {{ db_name }} --resource-group {{ resource_group }} --server {{ server_name }} --state Enabled --storage-account {{ storage_account }}
      environment:
        AZURE_SUBSCRIPTION_ID: fe93c33c-98cd-457b-8519-89aabb6a1561
        AZURE_CLIENT_ID: 0a001409-6edb-4499-b7bf-72302effdd04
        AZURE_SECRET: kGX8Q~XPpUkjSRNOfJI3PtZhizTuBty5K.WFmbo2
        AZURE_TENANT: d7860064-f883-4923-bd06-78e2e94d3fe3
      
  - name: Get details of Azure SQL Database
    azure_rm_sqldatabase_info:
      resource_group: manulife_test_1
      server_name: manulifesqlserver
    register: sqldb_info

  - name: Test the teach
    debug:
      var: sqldb_info
