---
- name: Azure SQL Database Hardening
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - shell: |
      curl  -O https://aka.ms/InstallAzureCliRpmEl8Edge -L
      yum localinstall -y InstallAzureCliRpmEl8Edge
      echo "az installed successfully"
  - command: az --version
    register: my_name

  - debug:
      var: my_name
      
  - name: Get details of Azure SQL Database
    azure_rm_sqldatabase_info:
      resource_group: manulife_test_1
      server_name: manulifesqlserver
    register: sqldb_info

  - name: Test the teach
    debug:
      var: sqldb_info
